<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:include filename="dimensions.xacro"/>
  <xacro:include filename="inertia_macros.xacro"/>

  <!--###############-->
  <!-- Front Casters -->
  <!--###############-->
  <xacro:macro name="front_caster" params="prefix x_reflect y_reflect">
    <link name="${prefix}_front_caster_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${front_caster_radius}" length="${front_caster_width}"/>
        </geometry>
        <material name="gray"/>
      </visual>

      <collision>
        <geometry>
          <sphere radius="${front_caster_radius}"/>
        </geometry>
      </collision>

      <xacro:inertial_sphere mass="0.5" radius="${front_caster_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
    </link>


    <joint name="${prefix}_front_caster_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_front_caster_link"/>
      <origin xyz="${x_reflect*front_caster_x_offset} ${y_reflect*front_caster_y_offset} ${-main_wheel_radius + front_caster_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_front_caster_link">
      <material>Gazebo/Black</material>
      
      <!-- Frictionless-ish -->
      <!-- Stops the robot from jumping around -->
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
    </gazebo>
  </xacro:macro>

  <!--##############-->
  <!-- Back Casters -->
  <!--##############-->
  <xacro:macro name="back_caster" params="prefix x_reflect y_reflect">
    <link name="${prefix}_back_caster_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${back_caster_radius}" length="${back_caster_width}"/>
        </geometry>
        <material name="gray"/>
      </visual>

      <collision>
        <geometry>
          <sphere radius="${back_caster_radius}"/>
        </geometry>
      </collision>

      <xacro:inertial_sphere mass="0.5" radius="${back_caster_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
    </link>


    <joint name="${prefix}_back_caster_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_back_caster_link"/>
      <origin xyz="${x_reflect*back_caster_x_offset} ${y_reflect*back_caster_y_offset} ${-main_wheel_radius + back_caster_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_back_caster_link">
      <material>Gazebo/Black</material>
      
      <!-- Frictionless-ish -->
      <!-- Stops the robot from jumping around -->
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
    </gazebo>
  </xacro:macro>

  <xacro:front_caster prefix="left" x_reflect="1" y_reflect="1" />
  <xacro:front_caster prefix="right" x_reflect="1" y_reflect="-1" />
  <xacro:back_caster prefix="left" x_reflect="-1" y_reflect="1" />
  <xacro:back_caster prefix="right" x_reflect="-1" y_reflect="-1" />
</robot>