<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">
  <!-- This file contains the dimensions of the robot -->
  <!-- The dimensions are defined in meters -->

  <!-- Convert mm to meters -->
  <xacro:property name="mm_to_m" value="${0.001}"/>
  <xacro:property name="cm_to_m" value="${0.01}"/>

  <!-- Convert inches to meters -->
  <xacro:property name="in_to_m" value="${0.0254}"/>

  <!-- Base Chassis Dimensions -->
  <xacro:property name="base_length" value="${0.508}"/>
  <xacro:property name="base_width" value="${0.406}"/>
  <xacro:property name="base_height" value="${0.406}"/>

  <!-- Wheel Dimensions / Location -->
  <xacro:property name="main_wheel_diameter" value="${33.02 * cm_to_m}"/>
  <xacro:property name="main_wheel_radius" value="${main_wheel_diameter / 2}"/>
  <xacro:property name="main_wheel_width" value="${48 * mm_to_m}"/>
  <xacro:property name="main_wheel_z_offset" value="${0.0}"/>
  <xacro:property name="main_wheel_y_offset" value="${28.575 * cm_to_m}"/>
  <xacro:property name="main_wheel_x_offset" value="${0.0}"/>

  <!-- Caster Dimensions / Location -->
  <xacro:property name="front_caster_diameter" value="${20.32 * cm_to_m}"/>
  <xacro:property name="front_caster_radius" value="${front_caster_diameter / 2}"/>
  <xacro:property name="front_caster_width" value="${16 * mm_to_m}"/>
  <xacro:property name="front_caster_z_offset" value="${(16.51 * cm_to_m) - ((10.16 / 2) * cm_to_m)}"/>
  <xacro:property name="front_caster_y_offset" value="${22.225 * cm_to_m}"/>
  <xacro:property name="front_caster_x_offset" value="${53.975 * cm_to_m}"/>

  <xacro:property name="back_caster_diameter" value="${15.24 * cm_to_m}"/>
  <xacro:property name="back_caster_radius" value="${back_caster_diameter / 2}"/>
  <xacro:property name="back_caster_width" value="${16 * mm_to_m}"/>
  <xacro:property name="back_caster_z_offset" value="${(16.51 * cm_to_m) - ((7.62 / 2) * cm_to_m)}"/>
  <xacro:property name="back_caster_y_offset" value="${26.9875 * cm_to_m}"/>
  <xacro:property name="back_caster_x_offset" value="${33.02 * cm_to_m}"/>

</robot>